### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by jetmcquack** [gcerretani/antenati#16]
Hello, I'm running the antenati script since long time. I haven't used it in a while and now I'm always getting a runtime error:
```
python3 antenati.py https://antenati.cultura.gov.it/ark:/12657/an_ua35390363/5BxaADy
Traceback (most recent call last):
  File "/Users/jetmcquack/Documents/Genealogia/tool antenati/antenati.py", line 231, in <module>
    main()
  File "/Users/jetmcquack/Documents/Genealogia/tool antenati/antenati.py", line 215, in main
    downloader = AntenatiDownloader(args.url, args.first, args.last)
  File "/Users/jetmcquack/Documents/Genealogia/tool antenati/antenati.py", line 42, in __init__
    self.manifest = self.__get_iiif_manifest(self.url)
  File "/Users/jetmcquack/Documents/Genealogia/tool antenati/antenati.py", line 104, in __get_iiif_manifest
    raise RuntimeError(f'{url}: HTTP error {http_reply.status}')
RuntimeError: https://antenati.cultura.gov.it/ark:/12657/an_ua35390363/5BxaADy: HTTP error 403

```

I'm doing something wrong or is there an issue?

**Comment by gcerretani** [comment]
Please update to the latest version of the script. I released a fix few days ago to deal with the URL change from https://www.antenati.san.beniculturali.it/ to https://antenati.cultura.gov.it/.
