### ISSUE TITLE
Sometimes the software suddenly fails (Mac OS)

### ISSUE THREAD

**Issue by kordan** [gcerretani/antenati#9]
git fetch origin --prune
git pull
python3 antenati.py "https://www.antenati.san.beniculturali.it/detail-registry/?s_id=19135478"
Traceback (most recent call last):
  File "/Users/kordan/Desktop/ALBERI/antenati/antenati.py", line 201, in <module>
    main()
  File "/Users/kordan/Desktop/ALBERI/antenati/antenati.py", line 186, in main
    downloader = AntenatiDownloader(args.url)
  File "/Users/kordan/Desktop/ALBERI/antenati/antenati.py", line 31, in __init__
    self.manifest = self.__get_iiif_manifest(self.archive_url)
  File "/Users/kordan/Desktop/ALBERI/antenati/antenati.py", line 63, in __get_iiif_manifest
    raise RuntimeError(f'{url}: HTTP error {http_reply.status}')
RuntimeError: https://www.antenati.san.beniculturali.it/detail-registry/?s_id=19135478: HTTP error 403

**Comment by gcerretani** [comment]
Not an issue of this program: 403 errors are related to the remote server, probably due to filters to prevent DDoS, introduced at the beginning of this year.

**Comment by gcerretani** [comment]
Please update to v2.3, it should help you by adding some workarounds to new SAN server filters.
